# Generated by Django 3.0.6 on 2020-05-08 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
