# Generated by Django 3.0.6 on 2020-05-08 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_search_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='search',
            old_name='count',
            new_name='hits',
        ),
    ]
